name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

env:
  version: ${{ github.run_number }}
        
jobs:     
  build:
    name: Docker image build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: ls -a

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          build-args: VERSION=${{ env.version }}
          push: true
          tags: ${{ secrets.DOCKER_USER }}/platform_eng:${{ env.version }} , ${{ secrets.DOCKER_USER }}/platform_eng:latest
